### ISSUE TITLE
Add support to "Spanish Wiktionary"

### ISSUE THREAD

**Issue by marreromarco** [lingua-libre/Lingua-Libre-Bot#20]
@belett @0x010C @Poslovitch @WikiLucas00 @hugolpz

**Would it be possible to add support to automatically add pronunciations to the Spanish Wiktionary ?**

The Spanish Wiktionary has very few pronunciations. As a native speaker, I would like to contribute with thousands of recordings, but it is not feasible to edit each Wiktionary entry manually.

Thank you very much in advance !

![image](https://user-images.githubusercontent.com/58692066/141409740-e2bc9fb4-fa3c-43ef-869c-e012a91510f6.png)

**Comment by Poslovitch** [comment]
Hi, please fill in the following template and post it on https://lingualibre.org/wiki/LinguaLibre:Bot. You can login through OAuth.
Aside from this, you will also have to make sure that the Spanish Wiktionary community is agreeing to use the bot and to grant it the bot flag after it is tested successfully.

```
== Bot request for {language} wiktionary ==
* '''Example pages (3):''' a few links to pages that are examples of the usual structure of the pages on your Wiktionary
* '''Target section:''' in which section the recordings should be listed (on the French Wiktionary, this is {{S|prononciation}})
* '''Local audio template(s) example(s):''' an example of how the audio recording template is used : e.g. {{deng|en|en-us-apple.ogg|Deng (DYA)}} 
* '''Local audio template(s) explained:''' explain the various parameters of the template (especially if the documentation of your template is not available in English nor in French)
** {Deng} means "audio", and take the following parameters...
** <code>en</code> is the iso639-2 of the audio.
** <code>en-us-apple.ogg</code> is the filename
** <code>Deng (DYA)</code> means audio (deng) and USA (DYA) which is the local variant or accent.
* '''Summary text: ''' the text you would like to be displayed on your wiki when Lingua Libre Bot adds a pronunciation on it.
* Request by: ~~~~
```

**Comment by hugolpz** [comment]
@marreromarco, we need some technical information. Please click [here](https://lingualibre.org/index.php?title=LinguaLibre:Bot&action=edit&editintro=Message&preloadtitle=Request%20for%20bot%20in%20{language}&preload=LinguaLibre:Bot%2Fform&section=new) to create a proper request. Then adapt to your needs. It will create a request and provide a guide with steps to follow. ✌🏼

**Comment by marreromarco** [comment]
<pre>== Bot request for {es} wiktionary ==
{{Bot steps}}
* '''Example pages (≥3): '''

Including audio:
https://es.wiktionary.org/wiki/comer
https://es.wiktionary.org/wiki/casa
https://es.wiktionary.org/wiki/Espa%C3%B1a
https://es.wiktionary.org/wiki/agua

Missing audio:
https://es.wiktionary.org/wiki/fresa
https://es.wiktionary.org/wiki/Francia
https://es.wiktionary.org/wiki/correr
https://es.wiktionary.org/wiki/r%C3%A1pido


* '''Target section:'''
{{pron-graf}} (OR {{pron-graf|leng=es}})  The target section is called either {{pron-graf}} or {{pron-graf|leng=es}}

Details about the structure of the Spanish Wiktionary (only in Spanish):
https://es.wiktionary.org/wiki/Plantilla:pron-graf


* '''Local audio template(s) example(s):'''
Template example:
{{pron-graf|leng=es
|pron=estándar|fone=paˈɾa.me.tɾos|audio=Example.ogg|fone2=paˈɾa.me.tɾoː|fono3=paˈra.me.tros


Actual examples from entries:
{{pron-graf|fone=esˈpa.ɲa|audio=Es-es españa 001.ogg}}

{{pron-graf|fone=koˈmeɾ|audio=LL-Q1321 (spa)-Rodelar-comer.wav}}

{{audio|Es-am-lat-casa.ogg|'''Audio''' (América)}}
{{audio|Es-bo-casa.oga|'''Audio''' (La Paz, Bolivia)}}

{{pron-graf|fone=ˈa.ɣwa|audio=Es-am-lat-agua.ogg|pron=América Latina|2audio=LL-Q1321 (spa)-Rodelar-agua.wav|2pron=España|2fone=ˈa.ɣwa}}


* '''Local audio template(s) explained:
** {pron-graf} refers to the "Pronunciation Box" where the IPA transcriptions and the audios are displayed together.
** <leng>es> is the iso639-2 of the audio.

* '''Edit summary text: '''
Añadido por LinguaLibre.org

* Request by: "Marreromarco" </pre>
email: wiki.nx6f7@simplelogin.co
