### ISSUE TITLE
Review/improve documentation

### ISSUE THREAD

**Issue by hugolpz** [lingua-libre/Lingua-Libre-Bot#3]
- [ ] Improve README.md so that junior hackers may board in and do things easily.
  - [x] Shorten the installation commands 
  - [x] Add _See also_ section with links
  - [x] Add _Structure_ section with files descriptions
  - [ ] Complete _Structure_ section. cc @CedricTarbouriech

**Comment by Poslovitch** [comment]
The README is in progress and will be updated alongside my work on the bot.

I will update Help:Bots once the README is "high quality" enough.

What's up with @belett ? As long as he works on separate branches and/or forks and he makes pull requests for the major changes, there shouldn't be any issues.

**Comment by hugolpz** [comment]
What up with Belett ? Just.... I'am begginer at managing Pull requests so I try to avoid complex situations where 2 people edits the same files... XD

**Comment by Poslovitch** [comment]
I can handle the PRs in case you find that complicated. We should just stick to having at least 1 code review if someone changes something in a way that significantly impacts others' work or their use of the services provided by LL.

**Comment by hugolpz** [comment]
Agree. We need one code reviewer whenever we can.

**Comment by Poslovitch** [comment]
>  Are you ok to become repository owner for LL Bot ?

I am. I'm taking over the bot for a year.

**Comment by hugolpz** [comment]
@CedricTarbouriech , I made some minor additions (https://github.com/lingua-libre/Lingua-Libre-Bot/commit/22341867f90574e8f2801c8f15f1e8dc3ff1e0d0) so the place (this repository & code) is friendlier to new comers. I added what I could, but the structure section may gain from your understanding.

**Comment by hugolpz** [comment]
Issue 90% done (Hugolpz).
Inactive for past 6 months.
Closed.
