### ISSUE TITLE
Get back control 🇬🇧 

### ISSUE THREAD

**Issue by hugolpz** [lingua-libre/Lingua-Libre-Bot#4]
- [x] Identify possible sources of passwords : 
  - `should be located in a file called config.ini in the bot's folder.` -- @Poslovitch

@mickeybarber, on wikimedia servers, can you :
- [x] find this `config.ini` file
- [x] find the LinguaLibre Bot's password
- [x] store it safely
- [x] share it securely with @Poslovitch
- [x] Tick all the boxes above and close this issue 🥇 😄 

Help : https://github.com/lingua-libre/operations/issues/2
```
├── Lingua-Libre-Bot
│   ├── config.ini
```

If no otherway : 
- [ ] Ask 0x010C's LinguaLibre bot's login access

**Comment by hugolpz** [comment]
@Poslovitch : do you thing the password may be somewhere on the servers as well ? If not, we ping 0x010C.
How does the bot, on the Wikimedia servers, connects on the wikimedia websites (Lili, Commons) if he does create a password-supported connection ?

**Comment by Poslovitch** [comment]
The connection is indeed password-based, and the credentials should be on the server hosting the bot. They should be located in a file called `config.ini` in the bot's folder.

**Comment by hugolpz** [comment]
- [ ] Ask @mickeybarber to find us this.

**Comment by hugolpz** [comment]
@mickeybarber, @Poslovitch : when you have shared LL-bot's password, please close this issue.

**Comment by Poslovitch** [comment]
The bot's credentials were shared to me.
